//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeelsBadMan_testi.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class SuperSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SuperSettings defaultInstance = ((SuperSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SuperSettings())));
        
        public static SuperSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.11239")]
        public double EURTOUSD {
            get {
                return ((double)(this["EURTOUSD"]));
            }
            set {
                this["EURTOUSD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.898963")]
        public double USDTOEUR {
            get {
                return ((double)(this["USDTOEUR"]));
            }
            set {
                this["USDTOEUR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.11239")]
        public double default_eurtousd {
            get {
                return ((double)(this["default_eurtousd"]));
            }
            set {
                this["default_eurtousd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.898963")]
        public double default_usdtoeur {
            get {
                return ((double)(this["default_usdtoeur"]));
            }
            set {
                this["default_usdtoeur"] = value;
            }
        }
    }
}
